### PR TITLE
Up Prisma Connection limit

### PR DESCRIPTION
**Pull request by hankewyczz**
# Purpose

Bump the Prisma connection limit. 

Also did some looking into two other issues:
- Updater dying in prod
  - This has two causes - the Prisma issue (which this should fix), and a `429` error. The latter is a consequence of our Elasticsearch instance size. I'm fine with that one - the task gets recreated anyways, so I think we can live with this (since it lets us keep the free tier) 
- Old courses not being deleted
  - See `ESLG 0080` for Spring 2022 - added some logging to help me track down the issue 
<br>

# Tickets

###### A link to any tickets this PR is associated with on Trello.

-https://trello.com/c/Kx93LHkv/276-fix-updater-dying-in-prod

# Contributors

###### Anyone who contributed to this PR for future reference.

-

# Feature List

###### A list of more in-depth and technical changes, additions, deletions, and fixes this PR provides.

-
-
-

# Notes

###### A list of miscellaneous notes for this pull request, such as whether we need to add something later for production, or that it was time boxed, etc.

<br>

# Checklist

- [x] Filled out PR template :wink:
- [ ] Approved by designers
- [x] Is passing linting checks
- [x] Is passing tsc
- [x] Is passing existing tests
- [x] Has documentation and comments in code
- [x] Has test coverage for code
- [x] Will have clear squash commit message

<br>
@sandboxnu/searchneu

### CODE REVIEW

**Review by megandouli — APPROVED** [review]
love bite sized PRs

**Review by megandouli — COMMENTED** [review]
looks like database test is failing?

**Review by andrewydai — APPROVED** [review]

**Comment by hankewyczz** [comment]
DB tests were failing (this is why i <3 workflow tests)

Added env interpolation, forced Prisma upgrade (`3.9.0` has an environment variable issue, so we need `^3.9.1`, and removed the `feature-preview` flag (which I forgot to remove earlier)

**Review by megandouli — APPROVED** [review]
cool @andrewydai we probably need to add a new environment variable

**Comment by hankewyczz** [comment]
@megandouli I wasn't sure about that - since the `prisma/.env` file is tracked by Git, will its variables be used, or does a new one still have to be inserted into Parameter Store?

If we need to add a new one, Parameter Store doesn't allow env variable interpolation, so we might have to add the connection limit to the variable itself

**Comment by megandouli** [comment]
> @megandouli I wasn't sure about that - since the `prisma/.env` file is tracked by Git, will its variables be used, or does a new one still have to be inserted into Parameter Store?
> 
> If we need to add a new one, Parameter Store doesn't allow env variable interpolation, so we might have to add the connection limit to the variable itself

oh hm you're right we might not need a new variable in the parameter store actually if the Prisma client uses the environment variable `DATABASE_URL` and does string interpolation to create the new environment variable

**Pull request merged**
